version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'exchange_rates'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'sergo'
    ports:
      - "5432:5432"

  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"



